set -e
true
true
/root/miniconda3/envs/genomeanalysis/bin/spades-hammer /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/corrected/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/python3 /root/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/compress_all.py --input_file /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/corrected/corrected.yaml --ext_python_modules_home /root/miniconda3/envs/genomeanalysis/share/spades --max_threads 16 --output_dir /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/corrected --gzip_output
true
true
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K21/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K33/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K55/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K77/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K99/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/configs/config.info
/root/miniconda3/envs/genomeanalysis/bin/python3 /root/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/before_rr.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/before_rr.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/assembly_graph_after_simplification.gfa /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/assembly_graph_after_simplification.gfa /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/final_contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/first_pe_contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/first_pe_contigs.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/strain_graph.gfa /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/strain_graph.gfa /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/scaffolds.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/scaffolds.fasta /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/scaffolds.paths /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/scaffolds.paths /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/assembly_graph_with_scaffolds.gfa /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/assembly_graph_with_scaffolds.gfa /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/assembly_graph.fastg /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/assembly_graph.fastg /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/K127/final_contigs.paths /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/contigs.paths
true
/root/miniconda3/envs/genomeanalysis/bin/python3 /root/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/scaffolds.fasta --misc_dir /mnt/c/Users/avinz/OneDrive/Desktop/genome-assembly-and-annotation/spadesout/misc --threshold_for_breaking_scaffolds 3
true
